version: '2'
services:

  testrpc:
    build: testrpc
    networks:
      - ethereum-dev

  parity-ropsten:
    image: ethcore/parity:beta-release
    volumes:
      - parity-ropsten-data:/var/parity
    tty: true
    networks:
      - ethereum-ropsten
    entrypoint: >
      /build/parity/target/release/parity
        --testnet --warp
        --ui-interface 0.0.0.0 --jsonrpc-interface 0.0.0.0 --dapps-interface 0.0.0.0
        --jsonrpc-hosts all --dapps-hosts all
        --base-path /var/parity

  oraclize-bridge:
    tty: true
    build: oraclize-bridge
    networks:
      - ethereum-dev
    links:
      - testrpc
    volumes:
      - oraclize-instance:/var/oraclize-bridge/config/instance

  oraclize-bridge-announce:
    tty: true
    build: oraclize-bridge-announce
    networks:
      - ethereum-dev
    links:
      - oraclize-bridge
    volumes:
      - oraclize-instance:/var/oraclize-instance
      - "${ETH}/containers/oraclize-bridge-announce/bin/server.js:/var/announce/server.js"
    ports:
      - "80"

  truffle:
    stdin_open: true
    tty: true
    build: truffle
    networks:
      - ethereum-dev
      - ethereum-ropsten
    volumes:
      - "${ETH}/dapps:/var/dapps"
    links:
      - parity-ropsten
      - testrpc
      - oraclize-bridge-announce

  nginx:
    restart: always
    tty: true
    image: nginx
    volumes:
      - "${ETH}/containers/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - ethereum-ropsten
    ports:
      - "80:80"
      - "8080:8080"
      - "8545:8545"
    links:
      - parity-ropsten
    entrypoint: >
      /bin/bash -c "nginx -g 'daemon off;'"


volumes:
  parity-ropsten-data:
    external: true
  oraclize-instance:

networks:
  ethereum-dev:
    driver: bridge
  ethereum-ropsten:
    driver: bridge
